### PR TITLE
Updated Google Mobile Ads to 7.42.2

### PR DESCRIPTION
**Pull request by obigu**
I've generated bindings for Google AdMob 7.42.2 from scratch (with an empty .yaml) using the latest Bro-gen.
Important considerations:
- The custom library to be able to use with Google Services has been removed as it was outdated (I guess now the option is to use Firebase Ads) and non mantained by anybody.
- Backwards compatibility may be broken due to .yaml clean up.
- Only Banners have been tested
- The documentation on initialization and usage is very outdated and it's not something I will have time to work on

For these reasons this PR Should Not be merged (unless contributed to complete) but it's fully functional in case anybody wants to use the latest AdMob version.

### CODE REVIEW

**Comment by dotw** [comment]
@obigu I want to says thanks and this PR saves my time. I'm using `GADRewardBasedVideoAd` in my APP with this PR and it works perfectly.

**Comment by SinaZK** [comment]
How should i use and test your branch? is there any release file that i can use?

**Comment by mustii82** [comment]
Ecountert this on Admob SDK 7.47.0

`2019-07-27 13:54:29.123 IOSLauncher[2012:58389] <Google> To get test ads on this device, set: request.testDevices = @[ kGADSimulatorID ];
2019-07-27 13:54:29.324 IOSLauncher[2012:58389] *** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized incorrectly. Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-update-plist to include the AppMeasurement framework, set the -ObjC linker flag, and set GADApplicationIdentifier with a valid App ID. Google Ad Manager publishers, follow instructions here: https://googlemobileadssdk.page.link/ad-manager-ios-update-plist'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001171d08db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000117abcac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001171d0449 -[NSException raise] + 9
	3   IOSLauncher                         0x000000010d62ef34 GADApplicationVerifyPublisherInitializedAnalyticsCorrectly + 263
	4   IOSLauncher                         0x000000010d5e0070 GAD_GADApplication_x86_64_7_47_0 + 2922
	5   IOSLauncher                         0x000000010d5e040d GAD_GADApplication_x86_64_7_47_0 + 3847
	6   IOSLauncher                         0x000000010d5e76e8 GADDispatchAsyncSafeMainQueue + 45
	7   IOSLauncher                         0x000000010d5e03e3 GAD_GADApplication_x86_64_7_47_0 + 3805
	8   IOSLauncher                         0x000000010d63b39d GAD_GADAdSource_x86_64_7_47_0 + 2096
	9   IOSLauncher                         0x000000010d64a3ff GAD_GADInterstitial_x86_64_7_47_0 + 3250
	10  IOSLauncher                         0x000000010d64a0bc GAD_GADInterstitial_x86_64_7_47_0 + 2415
	11  IOSLauncher                         0x000000010d5e76e8 GADDispatchAsyncSafeMainQueue + 45
	12  IOSLauncher                         0x000000010d649f90 GAD_GADInterstitial_x86_64_7_47_0 + 2115
	13  IOSLauncher                         0x000000010d649db6 GAD_GADInterstitial_x86_64_7_47_0 + 1641
	14  IOSLauncher                         0x000000010d4dd8a1 [J]org.robovm.objc.$M.objc_msgSend_object(Lorg/robovm/apple/foundation/NSObject;Lorg/robovm/objc/Selector;Lorg/robovm/apple/foundation/NSObject;)V + 175
	15  IOSLauncher                         0x000000010d4df3d7 [J]org.robovm.objc.$M.objc_msgSend_object_instance(Lorg/robovm/apple/foundation/NSObject;Lorg/robovm/objc/Selector;Lorg/robovm/apple/foundation/NSObject;)V + 85
	16  IOSLauncher                         0x000000010d4da9e3 [j]org.robovm.objc.$M.objc_msgSend_object_instance(Lorg/robovm/apple/foundation/NSObject;Lorg/robovm/objc/Selector;Lorg/robovm/apple/foundation/NSObject;)V[clinit] + 68
	17  IOSLauncher                         0x000000010d4fa590 [J]org.robovm.pods.google.mobileads.GADInterstitial.loadRequest(Lorg/robovm/pods/google/mobileads/GADRequest;)V + 37
	18  IOSLauncher                         0x000000010cd08e65 [J]com.xera.samsworld.IOSAdHandler.createAndLoadInterstitial()Lorg/robovm/pods/google/mobileads/GADInterstitial; + 119
	19  IOSLauncher                         0x000000010cd08ee9 [J]com.xera.samsworld.IOSAdHandler.initialize(Ljava/lang/String;I)V + 85
	20  IOSLauncher                         0x000000010ccefcd7 [J]com.xera.helper.Manager.AdManager.init()V + 141
	21  IOSLauncher                         0x000000010ccefa97 [j]com.xera.helper.Manager.AdManager.init()V[clinit] + 45
	22  IOSLauncher                         0x000000010cce4f42 [J]com.xera.core.SamGame.create()V + 628
	23  IOSLauncher                         0x000000010cb42db6 [J]com.badlogic.gdx.backends.iosrobovm.IOSGraphics.draw(Lorg/robovm/apple/glkit/GLKView;Lorg/robovm/apple/coregraphics/CGRect;)V + 315
	24  IOSLauncher                         0x000000010cb44061 [J]com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.draw(Lorg/robovm/apple/coregraphics/CGRect;)V + 38
	25  IOSLauncher                         0x000000010cb44131 [J]com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.$cb$drawRect$(Lcom/badlogic/gdx/backends/iosrobovm/IOSGraphics$1;Lorg/robovm/objc/Selector;Lorg/robovm/apple/coregraphics/CGRect;)V + 22
	26  IOSLauncher                         0x000000010cb43ed2 [j]com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.$cb$touchesMoved$withEvent$(Lcom/badlogic/gdx/backends/iosrobovm/IOSGraphics$1;Lorg/robovm/objc/Selector;JLorg/robovm/apple/uikit/UIEvent;)V[callback] + 500
	27  IOSLauncher                         0x000000010cb43f3b [j]com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.$cb$touchesMoved$withEvent$(Lcom/badlogic/gdx/backends/iosrobovm/IOSGraphics$1;Lorg/robovm/objc/Selector;JLorg/robovm/apple/uikit/UIEvent;)V[callback] + 605
	28  QuartzCore                          0x0000000115df9a95 -[CALayer display] + 180
	29  QuartzCore                          0x0000000115e0be77 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 359
	30  QuartzCore                          0x0000000115d7b24a _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 328
	31  QuartzCore                          0x0000000115db2606 _ZN2CA11Transaction6commitEv + 610
	32  UIKitCore                           0x00000001205232c3 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 128
	33  CoreFoundation                      0x0000000117137cbc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	34  CoreFoundation                      0x0000000117137480 __CFRunLoopDoBlocks + 336
	35  CoreFoundation                      0x0000000117131d04 __CFRunLoopRun + 1252
	36  CoreFoundation                      0x00000001171314d2 CFRunLoopRunSpecific + 626
	37  GraphicsServices                    0x00000001193ba2fe GSEventRunModal + 65
	38  UIKitCore                           0x0000000120509fc2 UIApplicationMain + 140
	39  IOSLauncher                         0x000000010d2ee340 [J]org.robovm.apple.uikit.UIApplication.main(ILorg/robovm/rt/bro/ptr/BytePtr$BytePtrPtr;Ljava/lang/String;Ljava/lang/String;)I + 195
	40  IOSLauncher                         0x000000010d2ed84b [J]org.robovm.apple.uikit.UIApplication.main([Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Class;)V + 944
	41  IOSLauncher                         0x000000010d2ec8c4 [j]org.robovm.apple.uikit.UIApplication.main([Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Class;)V[clinit] + 68
	42  IOSLauncher                         0x000000010cd09a55 [J]com.xera.samsworld.IOSLauncher.main([Ljava/lang/String;)V + 74
	43  IOSLauncher                         0x000000010d53749e _call0 + 142
	44  IOSLauncher                         0x000000010d52ca58 callVoidMethod + 96
	45  IOSLauncher                         0x000000010d52f163 rvmCallVoidClassMethodA + 259
	46  IOSLauncher                         0x000000010d52f233 rvmCallVoidClassMethod + 120
	47  IOSLauncher                         0x000000010d527916 rvmRun + 226
	48  IOSLauncher                         0x000000010d51d880 main + 301
	49  libdyld.dylib                       0x0000000117758541 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by obigu** [comment]
> How should i use and test your branch? is there any release file that i can use?

You need to check it out and build it locally

**Comment by pablitar** [comment]
Hey there! Any plan tu support Google Mobile Ads 7.50.0? There is a warning of using a deprecated API when submitting the app to the App Store:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

If there is no plan, maybe I can create the bindings myself, with a little guidance (I'm almost new to iOS development).

Thanks in advance!

PS: Thanks @obigu for this PR. It worked flawlessly.

**Comment by piotrros** [comment]
Can you update admob to 7.52.0 ? Older admob is broken on iOS 13.. Interstitial is truncated from the bottom. 

I've tried running bro-gen by myself and after a lot of struggle with installing all essential tools, I've hit the wall:

```
./bro-gen.rb /Users/piotr/Documents/pierdoly/robovm-bro-gen/generated /Users/piotr/Documents/pierdoly/robovm-robopods/google-mobile-ads/ios/src/main/bro-gen/google-mobile-ads.yaml 


Using libclang: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib
Clang version detected: [11, 0]
Processing /Users/piotr/Documents/pierdoly/robovm-robopods/google-mobile-ads/ios/src/main/bro-gen/google-mobile-ads.yaml...
./bro-gen.rb:1691:in `block in initialize': Unknown cursor kind 437 in enum at /var/folders/ds/dzclwb3x0_n50z4rglk1zdth0000gn/T/d20191118-24970-19sl622/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h.4.h:378:66 (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/ffi-clang-0.3.0/lib/ffi/clang/cursor.rb:255:in `block in visit_children'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-clang-0.3.0/lib/ffi/clang/cursor.rb:258:in `visit_children'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-clang-0.3.0/lib/ffi/clang/cursor.rb:258:in `visit_children'
	from ./bro-gen.rb:1678:in `initialize'
	from ./bro-gen.rb:2368:in `new'
	from ./bro-gen.rb:2368:in `block in process'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-clang-0.3.0/lib/ffi/clang/cursor.rb:255:in `block in visit_children'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-clang-0.3.0/lib/ffi/clang/cursor.rb:258:in `visit_children'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-clang-0.3.0/lib/ffi/clang/cursor.rb:258:in `visit_children'
	from ./bro-gen.rb:2356:in `process'
	from ./bro-gen.rb:3349:in `block in <main>'
	from ./bro-gen.rb:3202:in `each'
	from ./bro-gen.rb:3202:in `<main>'
```

I didn't even change anything. After successful build I'd try replacing admob files with the latest ones.

**Comment by obigu** [comment]
@pablitar @piotrros Have you tried using this bindings with 7.50.0 or 7.52.0? I don't think the API has changed, they should be compatible.

@piotrros Make sure you update to the latest versions
ffi (1.11.1)
ffi-clang (0.6.0)

And that you use latest version of Bro Gen from https://github.com/dkimitsa/robovm-bro-gen

If you still have issues you can request help on MobiVM gitter https://gitter.im/MobiVM/robovm

**Comment by piotrros** [comment]
I still cannot get this working (I've updated to versions you mentioned), however I've used your advice and used your bindings. I had to also replace GoogleMobileAds.framework and attach other required frameworks. After that I had to add these lines in Info.plist.xml:

```
    <key>GADApplicationIdentifier</key>
    <string>ca-app-pub-XXXXXXXXXXXXXXXXXXXXX</string>
    <key>GADIsAdManagerApp</key>
```

and.. it's working! :)

**Pull request merged**
