### PR TITLE
Add Yandex AppMetrica robopod

### PR DESCRIPTION
**Pull request by alex-dorokhov**
This request adds AppMetrica robopod. It is tested and it works.

There is an issue in YMMYandexMetricaPreloadInfo binding. I wasn't able to make bro-gen to generate methods for it. However, I believe this class is rarely needed, so this can be fixed later by me or someone else.

### CODE REVIEW

**Comment by florianf** [comment]
@Tom-Ski Is this useable?

**Comment by Tom-Ski** [comment]
Missed this, and I have no idea. If @alex-dorokhov wants to take responsibility for it then seems ok, would be good to have it under bro-gen though.

**Comment by alex-dorokhov** [comment]
@Tom-Ski I'm ready to take the responsibility, I'm using this library regularly.
There is also the [yaml file](https://github.com/MobiDevelop/robovm-robopods/pull/11/commits/c1bd8913ab7d84a38639af7f62bc30e5b94446b3#diff-56a6d4492b2c5bdec0b1b12f48cf28a6). Or what do you mean by "under bro-gen"?

**Comment by Tom-Ski** [comment]
Ah sorry, I misunderstood your comment, you used bro-gen but you weren't able to make YMMYandexMetricaPreloadInfo via bro-gen?

**Comment by alex-dorokhov** [comment]
@Tom-Ski correct. And because of this, *YMMYandexMetricaPreloadInfo* is absent. All other classes are there and generated with bro-gen.

**Comment by Tom-Ski** [comment]
Gotcha. Ok sounds good, thanks!

**Pull request merged**
